### ISSUE TITLE
Text input value is not readable

### ISSUE THREAD

**Issue by LouisAndrew** [ReAGEnT-WiSe2021-22/frontend-v2#29]
- https://github.com/ReAGEnT-WiSe2021-22/frontend-v2/blob/f1f32200e4a2905b5cd45df44a2251cd8a7ce47d/packages/search-engine/src/direflow-components/search-engine/App.tsx#L84
- https://github.com/ReAGEnT-WiSe2021-22/frontend-v2/blob/f1f32200e4a2905b5cd45df44a2251cd8a7ce47d/packages/search-engine/src/direflow-components/search-engine/App.tsx#L57
- 
![image](https://user-images.githubusercontent.com/61015467/146153800-d6c1fcde-c325-4a50-971d-56c469ce9b2a.png)

**Comment by NathanaelHermanto** [comment]
<img width="1440" alt="Screenshot 2021-12-18 at 15 15 34" src="https://user-images.githubusercontent.com/73997016/146644207-c8937f51-a3e0-4816-b0c6-f5d6fdbaeb2f.png">
it is readable from my site though

**Comment by LouisAndrew** [comment]
Would you mind trying it out on the live site: https://reagent-wise2021-22.github.io/frontend-v2/#/search-engine. 

Try explicitly setting the font color for the inputs. Now it's being inherited from its parent
![image](https://user-images.githubusercontent.com/61015467/146644554-2ee6e746-6993-480a-b3e7-8fd532beb06d.png)
